services:
   derper:
       image: ghcr.io/erisa/ts-derper:latest
       hostname: ${TS_DERP_HOSTNAME}
       volumes:
         - /lib/modules:/lib/modules:ro
         - ./certs:/root/derper/${TS_DERP_HOSTNAME}
         - tailscale-state:/var/lib/tailscale
       cap_add:
         - NET_ADMIN
         - NET_RAW
       env_file: .env
       ports:
         - "${TS_DERP_LISTEN_PORT}:4443/tcp"
         - "${TS_DERP_STUN_PORT}:3478/udp"
       restart: unless-stopped
       devices:
         - /dev/net/tun:/dev/net/tun

volumes:
  tailscale-state:
